music/urls.py
from django.conf.urls import url
from . import views

app_name = "music"

urlpatterns = [
    #/music/
    url(r'^$', views.Indexview.as_view(), name="index"),

    #/music/register/
    url(r'^register/$', views.UserFormView.as_view(), name="register"),

    #/music/123
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="details"),

    # /music/album/add/
    url(r"^album/add/$", views.AlbumCreate.as_view(), name="album-add"),

    #/music/album/123/
    url(r"^album/(?P<pk>[0-9]+)/$", views.AlbumUpdate.as_view(), name="album-update"),

    #/music/album/123/delete
    url(r"^album/(?P<pk>[0-9]+)/delete/$", views.AlbumDelete.as_view(), name="album-delete"),
]

newapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include("music.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    app_logo = models.FileField()

    def get_absolute_url(self):
        return reverse("music:details", kwargs={"pk": self.pk})

    def __str__(self):
        return self.artist + ", " + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_fav = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "email", "password"]

music/views.py
from django.views import generic
from music.models import Album
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from music.forms import UserForm
from django.core.urlresolvers import reverse_lazy


class Indexview (generic.ListView):
    template_name = "music/index.html"
    # default
    # context_object_name = "object_list"
    context_object_name = "all_albums"

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    template_name = "music/details.html"
    model = Album


class AlbumCreate(CreateView):
    model = Album
    fields = ["artist", "album_title", "genre", "app_logo"]


class AlbumUpdate(UpdateView):
    model = Album
    fields = ["artist", "album_title", "genre", "app_logo"]


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy("music:index")


class UserFormView(View):
    form_class = UserForm
    template_name = "music/registration_form.html"

    # Display Blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # Cleaned data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user.set_password(password)
            user.save()

            # return user objects if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("music:index")

            return render(request, self.template_name, {"form": form})

music/templates/music/album-template.html
{% for field123 in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field123.error }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field123.label_tag }}</label>
        <div class="col-sm-10">{{ field123 }}</div>
    </div>
{% endfor %}

music/templates/music/album_form.html
{% extends "music/base.html" %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panal-body">
                        <h3>Add new Album</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include "music/album-template.html" %}
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Musicz{% endblock %}</title>
    <!--including Static Files -->
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel = "stylesheet" type="text/css" href="{% static "music/style.css" %}" />
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!--Header -->
            <div class="navbar-header">
                <button type ="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
               </button>
            </div>

            <!--Items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="navbar-band" href="{% url "music:index" %}">Musicz</a>
                    </li>
                    <li class="">
                        <a href="{% url "music:index" %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url "music:index" %}">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url "music:album-add" %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends "music/base.html" %}
{% block title %}Songs{% endblock %}
{% block body %}
    <img src="{{ album.app_logo.url }}" style="width: 250px"/>
    <h2>{{ album.artist }}</h2>
    <h3>{{ album.album_title }}</h3>

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_fav %}
            <img src="http://i.imgur.com/b9b13Rd.png">
        {% endif %}
        </br>
    {% endfor %}
{% endblock %}

music/templates/music/index.html
{% extends "music/base.html" %}
{% block body %}
    {% if all_albums %}
        <h3>This is Albums list</h3>
            <ul>
                {% for album in all_albums %}
                    <li>
                        <a href = "{% url "music:details" album.id %}">{{ album.album_title }} </a>
                        <form action="{% url "music:album-delete" album.id %}" method="post" style="display: inline">
                            {% csrf_token %}
                            <input type="hidden" name=" album_id" value="{{album.id }}" />
                            <button type="submit" class="btn btn-defalut btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
    {% else %}
        <h3>You did not have album</h3>
    {% endif %}
{% endblock %}

music/templates/music/registration_form.html
{% extends "music/base.html" %}
{% block title %}Registration{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panal-body">
                        <h3>Create New Account</h3>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include "music/album-template.html" %}
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}